name: Bump version in git

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        run: |
          git config --global user.email "jdwills95+actions@gmail.com"
          git config --global user.name "Actions"
          git fetch --tags
          wget -O - https://raw.githubusercontent.com/jdwills95/internet-health-monitor-ui-app/main/bump/gitbump.sh | bash
          VERSION=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1)
          echo "Docker Tag Version: $VERSION"
          echo "Building Latest"
          docker build -t darthmanatee/internethealthloggerui:latest .
          echo "Tagging images"
          docker tag darthmanatee/internethealthloggerui:latest darthmanatee/internethealthloggerui:$VERSION
          echo "Pushing Tag $VERSION"
          docker push darthmanatee/internethealthloggerui:$VERSION
          echo "Pushing Tag latest"
          docker push darthmanatee/internethealthloggerui:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
